// react-webpack-es/src/Root.jsx
import React from 'react';
import { BrowserRouter, Switch, Route, Redirect } from 'react-router-dom';
import { cssRaw } from 'typestyle';

import * as routePathHelpers from '@app/helpers/routePath';

import App from '@app/components/App';

cssRaw(`
    html {
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
    body {
        margin: 0;
    }
    *,
    *::before,
    *::after {
        box-sizing: inherit;
    }
`);

class Root extends React.Component {
    render() {
        return (
            <BrowserRouter>
                <Switch>
                    <Redirect
                        exact={true}
                        from={routePathHelpers.routePathProvider.ROOT}
                        to={routePathHelpers.routePathProvider.APP}
                    />
                    <Route path={routePathHelpers.routePathProvider.APP} component={App} />
                </Switch>
            </BrowserRouter>
        );
    }
}

export default Root;

// vue-webpack-es/src/Root.vue
<template>
    <div id="root">
        <router-view />
    </div>
</template>

<script>
import Vue from 'vue';

export default Vue.extend({
    name: 'Root',
});
</script>

<style>
html {
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
*,
*::before,
*::after {
    box-sizing: inherit;
}
body {
    margin: 0;
    font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', '微软雅黑', Arial,
        sans-serif;
}
</style>
