// current/vue-rollup-ts-multi-bundles/src/components/app.vue
<template>
    <div class="container">
        <img class="logo" alt="Vue Logo" :src="logo" />
        <div class="nav">
            <router-link :to="routePathProvider.APP">Home</router-link> |
            <router-link :to="routePathProvider.DYNAMIC_COMP_TEST">Dynamic Component Test</router-link>
        </div>
        <router-view />
    </div>
</template>

<style>
body {
    margin: 0;
}
</style>

<style scoped>
.logo {
    width: 15rem;
    height: 15rem;
}
.nav {
    display: flex;
}
</style>

<style lang="less">
.container {
    height: 100vh;
    width: 100vw;
    background-color: #eee;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;

    div {
        font-size: 2rem;
        padding: 1rem;
        background-color: #ccc;
        border-radius: 0.8rem;
    }

    div:not(:last-child) {
        margin-bottom: 1rem;
    }

    section div {
        display: flex;
        justify-content: center;
        font-size: 2rem;
        padding: 1rem;
        background-color: #ccc;
        border-radius: 0.8rem;
    }

    section div:not(:last-child) {
        margin-bottom: 1rem;
    }
}
</style>

<script lang="ts">
import Vue from 'vue';

import * as routePathHelpers from '@app/helpers/route-path';

import logo from '@app/assets/logo.png';

if (process.env.NODE_ENV === 'development') {
    (async function () {
        console.log(
            'You have async support if you read this instead of "ReferenceError: regeneratorRuntime is not defined" error.',
        );
    })();
}

export default Vue.extend({
    name: 'App',
    data() {
        return {
            logo,
            onDevEnv: process.env.NODE_ENV === 'development',
            routePathProvider: routePathHelpers.routePathProvider,
        };
    },
});
</script>

// current/react-webpack-es/src/components/app.jsx
import React, { useState, useEffect } from 'react';
import { Route } from 'react-router-dom';
import { style, cssRule } from 'typestyle';

import * as routePathHelpers from '@/helpers/route-path';

import * as titleServices from '@/services/title';

import logo from '@/assets/logo.svg';

cssRule('body', {
    margin: 0,
});

const moduleStyles = {
    container: style({
        $debugName: 'container',
        minHeight: '100vh',
        width: '100vw',
        backgroundColor: '#eee',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        $nest: {
            '& > div': {
                display: 'flex',
                fontSize: '2rem',
                color: '#aaa',
                padding: '1rem',
                backgroundColor: '#ccc',
                borderRadius: '0.8rem',
            },
            '& > div:not(:last-child)': {
                marginBottom: '1rem',
            },
        },
    }),
    logo: style({
        width: '15rem',
        height: '15rem',
    }),
};

function App() {
    const [docTitle, setDocTitle] = useState('');

    useEffect(() => {
        if (process.env.NODE_ENV === 'development') {
            titleServices.requestTitle().then((response) => {
                setDocTitle(response.data.data);
                document.title = response.data.data;
            });
        }
    }, []);

    return (
        <div className={moduleStyles.container}>
            <img className={moduleStyles.logo} alt="React Logo" src={logo} />
            <Route
                exact={true}
                path={routePathHelpers.routePathProvider.APP}
                render={() => (
                    <>
                        <div>This is the home page...</div>
                        {process.env.NODE_ENV === 'development' && (
                            <div>{`If you see document's title changed to '${docTitle}', api mock works.`}</div>
                        )}
                    </>
                )}
            />
        </div>
    );
}

if (process.env.NODE_ENV === 'development') {
    (async () => {
        console.log(
            'You have async support if you read this instead of "ReferenceError: regeneratorRuntime is not defined" error.',
        );
    })();
}

export default App;
